package com.accesa.price_comparator.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity                     // Marks the class as a JPA entity (corresponding to a table in the DB)
@Table(name = "products")   // (Optional) specifies the table name; otherwise, it would default to "product"
@Data                       // Lombok: generates getter, setter, toString, equals, hashCode
@NoArgsConstructor          // Lombok: generates a no-args constructor (required by JPA)
public class Product {

    @Id                    // Indicates that the following field is the primary key (PK)
    private String id;      // product_id (e.g., "P001"). Stored as text, exactly as it appears in the CSV.

    private String name;            // product name (product_name)
    private String category;        // category (product_category)
    private String brand;           // product brand
    private double packageQuantity; // quantity (e.g., 1, 0.5, 500)
    // private double price;      // price value
    private String packageUnit;     // unit (e.g., "l", "kg", "g", "pcs")

    // Getter, setter, etc., are generated by @Data.
}
